GET http://localhost:3001/auth/users

###

POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "username": "AnastasiaAd",
  "password": "future_nat"
}

###

GET http://localhost:3001/auth/login
Content-Type: application/json

{
  "username": "newAnastasia",
  "password": "password"
}

###

POST http://localhost:3001/auth/logout

###

